apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Release.Name }}-app"
  name: "{{ .Release.Name }}-service"
spec:
  selector:
    app: "{{ .Release.Name }}-app"
  type: {{ .type }}
  ports:
    {{- range .Values.service.ports }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}