apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  labels
    app: "{{ .Release.Name }}-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-app"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-app"
    spec:
      {{- with .Values.container }}
      containers:
      - image: "{{ .image.name }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.imagePullPolicy }}
        name: {{ .name }}
        ports:
        - name: {{ .port.name }}
          containerPort: {{ .port.number }}
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: {{ .secretName }}
              key: mongodb-uri
      {{- end }}
