apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  labels:
    app: "{{ .Release.Name }}-app"
spec:
  {{- with .Values.database }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: "{{ $.Release.Name }}-app"
  template:
    metadata:
      labels:
        app: "{{ $.Release.Name }}-app"
    spec:
      containers:
        - image: "{{ .container.image.name }}:{{ .container.image.tag }}"
          env:
          - name: MONGO_INITDB_DATABASE
            value: guestbook
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-password
          name: {{ .container.name }}
          ports:
            {{- range .container.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          volumeMounts:
            - name: {{ .container.volumeMounts.name }}
              mountPath: {{ .container.volumeMounts.mountPath }}
      volumes:
        {{- range .container.volumes}}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
        {{- end }}
  {{- end }}
