kind: PersistentVolume
apiVersion: v1
metadata:
  name: "{{ .Release.Name}}-pv"
  labels:
    type: {{ .Values.database.labels.type }}
spec:
  {{- with .Values.database }}
  storageClassName: {{ .storageClassName }}
  capacity:
    storage: {{ .resources.requests.storage }}
  accessModes: {{ .accessModes }}
  hostPath:
    path:  {{ .hostPath.path | quote }}
  {{- end }}
