apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-pvc"
spec:
  {{- with .Values.database }}
  storageClassName: {{ .storageClassName }}
  accessModes: {{ .accessModes }}
  resources:
    requests:
      storage: {{ .resources.requests.storage }}
  {{- end }}