container:
  name: frontend
  image:
    name: phico/frontend
    tag: "2.0"
    imagePullPolicy: Always
  ports:
  - name: frontend
    containerPort: 4200
  configMapName: frontend-config

service:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 4200

ingress:
  rules:
  - host: "frontend.minikube.local"
    paths:
    - path: /
      pathType: Prefix
      service:
        name: backend
        port:
          number: 80